name: circuit_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.13.0
  provider: ^6.1.4
  image_picker: ^1.1.2
  ollama_dart: ^0.2.2+1
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.2.1
  get: ^4.6.6
  permission_handler: ^11.0.1
  lottie: ^3.2.0
  chat_bubbles: ^1.7.0
  quickalert: ^1.1.0
  google_sign_in: ^5.4.4
  flutter_svg: ^2.1.0
  ionicons: ^0.2.2
  flutter_launcher_icons: ^0.14.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/play_store_512.png"
  min_sdk_android: 23
  adaptive_icon_background: "#18373E"
  adaptive_icon_foreground: "assets/play_store_512.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
